; Script generated by the Inno Setup Script Wizard.

#define MyAppName "AutoPublisher"
#define MyAppVersion "0.0.1"
#define MyAppExeName "main.exe"

[Setup]
AppId={{8D680B01-3B0A-4203-AE1F-1A25F1DB1372}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputBaseFilename=AutoPublisher_Setup
SetupIconFile=D:\100_Work\101_Program\Proj\XHS\logo.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "D:\100_Work\101_Program\Proj\XHS\build\main.dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\100_Work\101_Program\Proj\XHS\build\main.dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; 内置 Playwright Chromium 浏览器
Source: "C:\Users\19396\AppData\Local\ms-playwright\chromium-1208\*"; DestDir: "{localappdata}\ms-playwright\chromium-1208"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
